import type { Metadata } from "next";
import { Sour_Gummy, Poppins } from "next/font/google";
import "./globals.css";

const sourGummy = Sour_Gummy({
    variable: "--font-sour-gummy",
});

const poppings = Poppins({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    variable: "--font-poppins",
});

export const metadata: Metadata = {
    title: "Petstation Cardiff",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${poppings.className} ${sourGummy.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
